[project]
name = "day13-k4-observability"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "anh-dz", email = "nmnanh1235@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi==0.118.0",
    "httpx==0.28.1",
    "langfuse==3.2.1",
    "pydantic==2.11.4",
    "pytest==8.3.5",
    "python-dotenv==1.1.0",
    "pyyaml==6.0.3",
    "streamlit>=1.61.1",
    "structlog==25.4.0",
    "uvicorn[standard]==0.37.0",
]

[project.scripts]
day13-k4-observability = "day13_k4_observability:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
